# Generated by Django 3.1.6 on 2021-03-02 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSP',
            fields=[
                ('dsp_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('artists', models.CharField(max_length=256)),
                ('isrc', models.CharField(max_length=12)),
                ('usages', models.PositiveIntegerField()),
                ('revenue', models.DecimalField(decimal_places=15, max_digits=30)),
            ],
            options={
                'db_table': 'dsp',
            },
        ),
        migrations.AlterField(
            model_name='dsr',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsrs', to='dsrs.currency'),
        ),
        migrations.AlterField(
            model_name='dsr',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsrs', to='dsrs.territory'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='local_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territories', to='dsrs.currency'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(fields=('name', 'code'), name='currency_name_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='dsr',
            constraint=models.UniqueConstraint(fields=('path', 'period_start', 'period_end', 'territory', 'currency'), name='dsr_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='territory',
            constraint=models.UniqueConstraint(fields=('name', 'code_2'), name='territory_name_code_unique'),
        ),
        migrations.AddField(
            model_name='dsp',
            name='dsr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dsps', to='dsrs.dsr'),
        ),
    ]
