# Generated by Django 3.1.7 on 2021-03-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0002_auto_20210302_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsp',
            name='revenue',
            field=models.DecimalField(decimal_places=19, max_digits=40),
        ),
    ]
